[project]
name = "open-review"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "dotenv>=0.9.9",
    "openreview-py>=1.52.6",
    "pandas>=2.3.3",
]
